#' Create html table with the results of the evaluation
#'
#' This function generates an HTML table to visualize the results of the assessment
#' performed by \code{assess}. It applies specific formatting and color coding
#' based on the evaluation schema used (INE, CEPAL 2020, CEPAL 2023, or Economics).
#'
#' @param table A \code{dataframe} generated by the \code{assess} function.
#'              It must have a class attribute indicating the evaluation scheme
#'              (e.g., "ine.eval", "cepal2020.eval").
#'
#' @return A \code{knitr_kable} object representing the HTML table.
#'
#' @import kableExtra
#' @importFrom dplyr mutate mutate_if case_when
#'
#' @examples
#' \dontrun{
#' library(survey)
#' library(dplyr)
#'
#' # Example design
#' dc <- svydesign(ids = ~varunit, strata = ~varstrat,
#'                 data = epf_personas %>% group_by(folio) %>% slice(1),
#'                 weights = ~fe)
#'
#' # Create estimation and assess
#' est <- create_mean("gastot_hd", domains = "zona", design = dc)
#' evaluation <- assess(est)
#'
#' # Generate HTML table
#' create_html(evaluation)
#' }
#' @export

create_html <- function(table) {

  # --- 1. ESTÁNDAR INE ---
  if (inherits(table, "ine.eval")) {
    table %>%
      dplyr::mutate_if(is.numeric, ~round(.x, 2)) %>%
      dplyr::mutate(
        label = kableExtra::cell_spec(.data$label, background = dplyr::case_when(
          .data$label == "reliable" ~ "green",
          .data$label == "weakly reliable" ~ "yellow",
          .data$label == "non-reliable" ~ "red",
          TRUE ~ "white"
        ), color = "black"),
        n = kableExtra::cell_spec(.data$n, color = dplyr::case_when(
          .data$n < 60 ~ "red",
          TRUE ~ "black"
        )),
        df = kableExtra::cell_spec(.data$df, color = dplyr::case_when(
          .data$df < 9 ~ "red",
          TRUE ~ "black"
        ))) %>%
      .apply_kable_styling()

    # --- 2. ESTÁNDAR CEPAL 2020 ---
  } else if (inherits(table, "cepal2020.eval")) {
    table %>%
      dplyr::mutate_if(is.numeric, ~round(.x, 2)) %>%
      dplyr::mutate(
        label = kableExtra::cell_spec(.data$label, background = dplyr::case_when(
          .data$label == "reliable" ~ "green",
          .data$label == "weakly reliable" ~ "yellow",
          .data$label == "non-reliable" ~ "red",
          TRUE ~ "white"
        ), color = "black"),
        n = kableExtra::cell_spec(.data$n, color = dplyr::case_when(
          .data$n < 60 ~ "red",
          TRUE ~ "black"
        )),
        df = kableExtra::cell_spec(.data$df, color = dplyr::case_when(
          .data$df < 9 ~ "red",
          TRUE ~ "black"
        ))) %>%
      .apply_kable_styling()

    # --- 3. ESTÁNDAR CEPAL 2023 ---
  } else if (inherits(table, "cepal2023.eval")) {
    table %>%
      dplyr::mutate_if(is.numeric, ~round(.x, 2)) %>%
      dplyr::mutate(
        label = kableExtra::cell_spec(.data$label, background = dplyr::case_when(
          .data$label == "reliable" ~ "green",
          .data$label == "weakly reliable" ~ "yellow",
          .data$label == "non-reliable" ~ "red",
          TRUE ~ "white"
        ), color = "black"),
        n = kableExtra::cell_spec(.data$n, color = dplyr::case_when(
          .data$n < 60 ~ "red",
          TRUE ~ "black"
        )),
        df = kableExtra::cell_spec(.data$df, color = dplyr::case_when(
          .data$df < 9 ~ "red",
          TRUE ~ "black"
        ))) %>%
      .apply_kable_styling()

    # --- 4. ESTÁNDAR ECONÓMICAS ---
  } else if (inherits(table, "economicas.eval")) {
    table %>%
      dplyr::mutate_if(is.numeric, ~round(.x, 2)) %>%
      dplyr::mutate(
        label = kableExtra::cell_spec(.data$label, background = dplyr::case_when(
          # Etiquetas corregidas: reliable, weakly reliable, non-reliable
          .data$label == "reliable" ~ "green",
          .data$label == "weakly reliable" ~ "yellow",
          .data$label == "non-reliable" ~ "red",
          TRUE ~ "white"
        ), color = "black"),
        n = kableExtra::cell_spec(.data$n, color = dplyr::case_when(
          .data$n < 60 ~ "red",
          TRUE ~ "black"
        )),
        df = kableExtra::cell_spec(.data$df, color = dplyr::case_when(
          .data$df < 9 ~ "red",
          TRUE ~ "black"
        ))) %>%
      .apply_kable_styling()
  }
}

#' Helper interno para ponerle letras comunes, revisar acá que la documentación que leí decía que era weno
#' @keywords internal
.apply_kable_styling <- function(df_styled) {
  df_styled %>%
    kableExtra::kable(format.args = list(decimal.mark = ',', big.mark = "."),
                      format = "html",
                      escape = FALSE,
                      align = "c",
                      table.attr = "style = \"color: black;\"") %>%
    kableExtra::kable_styling("striped",
                              full_width = FALSE,
                              html_font = "arial") %>%
    kableExtra::kable_paper("hover") %>%
    kableExtra::row_spec(0, bold = TRUE, color = "black")
}
