#' Create html table with the results of the evaluation
#'
#' This function generates an HTML table to visualize the results of the assessment
#' performed by \code{assess}. It applies specific formatting and color coding
#' based on the evaluation schema used (INE, CEPAL 2020, CEPAL 2023, or Economics).
#'
#' @param table A \code{dataframe} generated by the \code{assess} function.
#'              It must have a class attribute indicating the evaluation scheme
#'              (e.g., "ine.eval", "cepal2020.eval").
#'
#' @return A \code{knitr_kable} object representing the HTML table.
#'
#' @import kableExtra
#' @importFrom dplyr mutate mutate_if case_when if_else
#'
#' @export

create_html <- function(table) {

  # --- 1. ESTÁNDAR INE ---
  if (inherits(table, "ine.eval")) {
    table %>%
      dplyr::mutate_if(is.numeric, ~round(.x, 2)) %>%
      dplyr::mutate(
        label = kableExtra::cell_spec(.data$label, background = dplyr::case_when(
          .data$label == "reliable" ~ "green",
          .data$label == "weakly reliable" ~ "yellow",
          .data$label == "non-reliable" ~ "red",
          TRUE ~ "white"
        ), color = "black"),

        # Semáforo parapersonas de n y df
        n = kableExtra::cell_spec(.data$n, color = "black", background = dplyr::case_when(
          grepl("insufficient", .data$eval_n) ~ "red",
          TRUE ~ "white"
        )),
        df = kableExtra::cell_spec(.data$df, color = "black", background = dplyr::case_when(
          grepl("insufficient", .data$eval_df) ~ "red",
          TRUE ~ "white"
        )),

        # Semáforo para CV, solo lo aplicamos si existe la columna eval_cv y dice "cv >"
        # no hay nigún otro color aun, la javi aun no dice de ponerle verde si es que está bien en verdad.
        cv = if("eval_cv" %in% names(table)) {
          kableExtra::cell_spec(.data$cv, color = "black", background = dplyr::case_when(
            grepl("cv >", .data$eval_cv) ~ "red",
            grepl("between", .data$eval_cv) ~ "yellow",
            TRUE ~ "white"
          ))
        } else { .data$cv },

        # Semáforo para SE (Error Estándar), solo lo aplicamos si existe la columna eval_se y dice "high"
        # lo mimsmo acá au
        se = if("eval_se" %in% names(table)) {
          kableExtra::cell_spec(.data$se, color = "black", background = dplyr::case_when(
            grepl("high", .data$eval_se) ~ "yellow",
            TRUE ~ "white"
          ))
        } else { .data$se }

      ) %>%
      .apply_kable_styling()

    # --- 2. ESTÁNDAR CEPAL 2020 ---
  } else if (inherits(table, "cepal2020.eval")) {
    table %>%
      # no hay que poner la traducción forzada, demasiada innovación

      dplyr::mutate_if(is.numeric, ~round(.x, 2)) %>%
      dplyr::mutate(
        label = kableExtra::cell_spec(.data$label, background = dplyr::case_when(
          .data$label == "publish" ~ "green",
          .data$label == "review" ~ "yellow",
          .data$label == "supress" ~ "red",
          TRUE ~ "white"
        ), color = "black"),

        # 1. n y df genericos
        n = kableExtra::cell_spec(.data$n, color = "black", background = dplyr::case_when(
          grepl("insufficient", .data$eval_n) ~ "red",
          TRUE ~ "white"
        )),

        # Ojo: df y cv en CEPAL 2020 son amarillos (review), no rojos.
        df = kableExtra::cell_spec(.data$df, color = "black", background = dplyr::case_when(
          grepl("insufficient", .data$eval_df) ~ "yellow",
          TRUE ~ "white"
        )),
        cv = kableExtra::cell_spec(.data$cv, color = "black", background = dplyr::case_when(
          grepl("non adequate", .data$eval_cv) ~ "yellow",
          TRUE ~ "white"
        )),

        # 3. Tamaño Efectivo de la muestra (ESS)
        ess = if("eval_ess" %in% names(table)) {
          kableExtra::cell_spec(.data$ess, color = "black", background = dplyr::case_when(
            grepl("insufficient", .data$eval_ess) ~ "red",
            TRUE ~ "white"
          ))
        } else { .data$ess },

        # 4. Conteo no ponderado, el coso de Unweighted
        unweighted = if("eval_unweighted" %in% names(table)) {
          kableExtra::cell_spec(.data$unweighted, color = "black", background = dplyr::case_when(
            grepl("insufficient", .data$eval_unweighted) ~ "red",
            TRUE ~ "white"
          ))
        } else { .data$unweighted }

      ) %>%
      .apply_kable_styling()

    # --- 3. ESTÁNDAR CEPAL 2023 ---
  } else if (inherits(table, "cepal2023.eval")) {
    table %>%
      # LIMPIEZA: weakly-reliable -> weakly reliable (sin guion)
      dplyr::mutate(label = dplyr::case_when(
        label == "weakly-reliable" ~ "weakly reliable",
        TRUE ~ label
      )) %>%
      dplyr::mutate_if(is.numeric, ~round(.x, 2)) %>%
      dplyr::mutate(
        label = kableExtra::cell_spec(.data$label, background = dplyr::case_when(
          .data$label == "reliable" ~ "green",
          .data$label == "weakly reliable" ~ "yellow",
          .data$label == "non-reliable" ~ "red",
          TRUE ~ "white"
        ), color = "black"),

        # CEPAL 23 a veces no trae eval_n, usamos una lógica para esto
        n = kableExtra::cell_spec(.data$n, color = "black", background = dplyr::case_when(
          .data$n < 60 ~ "red",
          TRUE ~ "white"
        )),
        df = kableExtra::cell_spec(.data$df, color = "black", background = dplyr::case_when(
          !grepl("Sufficient", .data$eval_df) ~ "red",
          TRUE ~ "white"
        ))) %>%
      .apply_kable_styling()

    # --- 4. ESTÁNDAR ECONÓMICAS ---
  } else if (inherits(table, "economicas.eval")) {
    table %>%
      dplyr::mutate_if(is.numeric, ~round(.x, 2)) %>%
      dplyr::mutate(
        # 1. Semáforo Etiqueta "normal"
        label = kableExtra::cell_spec(.data$label, background = dplyr::case_when(
          .data$label == "reliable" ~ "green",
          .data$label == "weakly reliable" ~ "yellow",
          .data$label == "non-reliable" ~ "red",
          TRUE ~ "white"
        ), color = "black"),

        # 2. n y df Rojo si eval dice insufficient y hay que funarlo
        n = kableExtra::cell_spec(.data$n, color = "black", background = dplyr::case_when(
          grepl("insufficient", .data$eval_n) ~ "red",
          TRUE ~ "white"
        )),
        df = kableExtra::cell_spec(.data$df, color = "black", background = dplyr::case_when(
          grepl("insufficient", .data$eval_df) ~ "red",
          TRUE ~ "white"
        )),

        # 3. CV (Si existe y es alto)
        cv = if("eval_cv" %in% names(table)) {
          kableExtra::cell_spec(.data$cv, color = "black", background = dplyr::case_when(
            grepl("cv >", .data$eval_cv) ~ "red",
            grepl("between", .data$eval_cv) ~ "yellow",
            TRUE ~ "white"
          ))
        } else { .data$cv },

        # 4. SE, si existe y es alto = "high SE"
        se = if("eval_se" %in% names(table)) {
          kableExtra::cell_spec(.data$se, color = "black", background = dplyr::case_when(
            grepl("high", .data$eval_se) ~ "yellow",
            TRUE ~ "white"
          ))
        } else { .data$se },

        # 5. Tasa de Cumplimiento, lo que pidió la javi
        # Aquí miramos el NA como indirectamente?: si es NA, el eval dice "insufficient" -> Rojo
        # CORRECCIÓN DE FLUJO: Solo pintamos rojo si FALLA n Y FALLA tasa, según el ppt
        compliance_rate = if("eval_compliance_rate" %in% names(table)) {
          kableExtra::cell_spec(.data$compliance_rate, color = "black", background = dplyr::case_when(
            (grepl("insufficient", .data$eval_n) & grepl("insufficient", .data$eval_compliance_rate)) ~ "red",
            TRUE ~ "white"
          ))
        } else { .data$compliance_rate }

      ) %>%
      .apply_kable_styling()
  }
}

#' Helper interno para temas de formato y letras
#' @keywords internal
.apply_kable_styling <- function(df_styled) {
  df_styled %>%
    kableExtra::kable(format.args = list(decimal.mark = ',', big.mark = "."),
                      format = "html", escape = FALSE, align = "c",
                      table.attr = "style = \"color: black;\"") %>%
    kableExtra::kable_styling("striped", full_width = FALSE, html_font = "arial") %>%
    kableExtra::kable_paper("hover") %>%
    kableExtra::row_spec(0, bold = TRUE, color = "black")
}
